- name: Show interface status on Catalyst
  hosts: switches
  gather_facts: no
  tasks:
    - name: Run show interface status
      cisco.ios.ios_command:
        commands:
          - show interface status
      register: interface_status

    - name: Print output
      debug:
        var: interface_status.stdout_lines
